# Generated by Django 3.1 on 2020-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_desc', models.TextField(default=' ', max_length=500)),
                ('event_venue', models.CharField(blank=True, default='', max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_closing', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
